# This is a generated file. Not intended for manual editing.
services:
  web.api:
    build:
      context: "/Users/diegosanches/Documents/Repos/DSM/DSM-licence-handler"
      dockerfile: "src/Web.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57408"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "webapi:dev"
    ports:
    - "127.0.0.1:57008:57000"
    - "127.0.0.1:57208:57200"
    - "127.0.0.1:57408:57408"
    volumes:
    - "/Users/diegosanches/Documents/Repos/DSM/DSM-licence-handler/src/Web.API:/app:rw"
    - "/Users/diegosanches/Documents/Repos/DSM/DSM-licence-handler:/src:rw"
    - "/Users/diegosanches/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/diegosanches/.local/share/JetBrains/RiderRemoteDebugger/2025.1.2/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/diegosanches/Library/Logs/JetBrains/Rider2025.1/DebuggerWorker/JetBrains.Debugger.Worker.2025_6_11_17_03_04:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
